Implement PointsList#copy() and JTSPoints#copy()
deegree/deegree3 pull request #1353
Opened 2022-06-27 15:42 UTC by dstenger

Interface org.deegree.geometry.primitive.Point was enhanced by copy() method.

Afterwards, PointReference and DefaultPoint were enhanced by implementations of this new method.

Finally, PointsList#copy() could be implemented.
JTSPoints#copy() was also implemented.

2022-07-27 16:42 UTC, tfr42 requested changes
Revisit the implementation blocks for clone() and copy() if they can be adapted.

2022-07-27 16:43 UTC, stephanr commented
During the TMC meeting the question came up if the introduction of copy() is useful while the existing API already uses clone(). (And copy() seems to come from a JTS interface in https://github.com/deegree/deegree3/blob/main/deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/points/Points.java)

2022-08-10 16:01 UTC, stephanr approved these changes

2022-08-10 16:01 UTC, tfr42 approved these changes

2022-08-10 16:01 UTC, merged